server:
  port: 8081

spring:
  config:
    import:
      - optional:application-telegram.yml
      - optional:application-finnhub.yml
      - optional:application-marketaux.yml
      - optional:application-spaceflight.yml
      - optional:application-subscription.yml
      - optional:application-email.yml
      - optional:application-watchlist.yml
  main:
    web-application-type: none
